-- TABLE CREATION (CREATE)
CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT,DEPARTMENT_NAME VARCHAR(100));
CREATE TABLE LOCATION(LOCATION_ID INT,LOCATION VARCHAR(30));
CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT,EMPLOYEE_NAME VARCHAR(50),GENDER ENUM('M','F'),AGE INT,HIRE_DATE DATE,DESIGNATION VARCHAR(100),DEPARTMENT_ID INT,LOCATION_ID INT,SALARY DECIMAL(10,2));

-- TABLE ALTERATION (ALTER)
ALTER TABLE EMPLOYEES ADD COLUMN EMAIL VARCHAR(20);
ALTER TABLE EMPLOYEES MODIFY DESIGNATION TEXT;
ALTER TABLE EMPLOYEES DROP COLUMN AGE;
ALTER TABLE EMPLOYEES RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;

-- TABLE RENAMING (RENAME) 
RENAME TABLE DEPARTMENTS TO DEPARTMENTS_INFO;
RENAME TABLE LOCATION TO LOCATIONS;

-- TABLE TRUNCATION (TRUNCATE)
TRUNCATE TABLE EMPLOYEES;

-- DATABASE & TABLE DROPPING (DROP)
DROP TABLE EMPLOYEES;
DROP DATABASE EMPLOYEE;

-- CONSTRAINTS
-- DATABASE RECREATION
DROP DATABASE IF EXISTS EMPLOYEES;
CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;

-- DEPARTMENTS TABLE
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,DEPARTMENT_NAME VARCHAR(100) UNIQUE NOT NULL);

-- LOCATION TABLE
CREATE TABLE LOCATION(LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,LOCATION VARCHAR(30) UNIQUE NOT NULL);

-- EMPLOYEES TABLE
CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT AUTO_INCREMENT KEY,EMPLOYEE_NAME VARCHAR(50) NOT NULL,GENDER ENUM('M','F'),AGE INT CHECK (AGE >= 18),
HIRE_DATE DATE DEFAULT (CURDATE()),DESIGNATION VARCHAR(100),
DEPARTMENT_ID INT,LOCATION_ID INT,FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),SALARY DECIMAL(10,2));


